version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: 'Generate Go code from sso proto files'
    dir: 'protos'
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative
  start_sso_local:
    desc: 'Start SSO microservice application'
    env:
      CONFIG_PATH: 'config/local.yaml'
    cmds:
      - go run cmd/sso/main.go --config=$CONFIG_PATH